import { CalendarDays, CheckCircle2, Clock, Download, Eye, FileText, MoreHorizontal, Search, Upload, UserPlus } from "lucide-react";
import { DashboardShell } from "@/components/dashboard-shell";
import { Card, Badge } from "@/components/ui";

const studentData: Record<string,{title:string;description:string;active:string;emoji:string;items:string[]}> = {
  "free-lessons": {title:"Free Lessons",description:"Watch topic-based videos and download learning notes.",active:"Free Lessons",emoji:"▶️",items:["Cells and Living Systems","Force, Work and Energy","Acids, Bases and Salts"]},
  timetable: {title:"Weekly Timetable",description:"Your personal class schedule for the current week.",active:"Weekly Timetable",emoji:"📅",items:["Grade 10 theory • Saturday 8:30 AM","Zoom revision • Wednesday 5:00 PM","Paper discussion • Sunday 1:30 PM"]},
  "live-classes": {title:"Live Classes",description:"Join scheduled Zoom classes and access class notes.",active:"Live Classes",emoji:"💻",items:["Live now: Electricity revision","Upcoming: Human body systems","Completed: Chemical reactions"]},
  assignments: {title:"Assignments",description:"Review pending, submitted, graded and overdue work.",active:"Assignments",emoji:"📝",items:["Assignment 06 • Due tomorrow","Model Paper 03 • Submitted","Cell Structure Quiz • 18/20"]},
  payments: {title:"Payments",description:"View current fees and submit a payment-slip UI.",active:"Payments",emoji:"💳",items:["August class fee • LKR 3,200","Bank transfer instructions","Payment slip upload area"]},
  "payment-history": {title:"Payment History",description:"Track submitted and approved monthly class fees.",active:"Payment History",emoji:"🧾",items:["July 2026 • Approved","June 2026 • Approved","May 2026 • Approved"]},
  attendance: {title:"Attendance",description:"See monthly attendance, history and class participation.",active:"Attendance",emoji:"✅",items:["Overall attendance • 92%","Present classes • 23","Absent classes • 2"]},
  notifications: {title:"Notifications",description:"Important class, assignment and payment alerts.",active:"Notifications",emoji:"🔔",items:["Assignment due tomorrow","Class time updated","Payment approved"]},
  profile: {title:"Student Profile",description:"Personal, guardian and academic information.",active:"Profile",emoji:"👩‍🎓",items:["Student ID • PU-2026-1048","Grade • 10","Parent contact • Mock information"]},
  settings: {title:"Settings",description:"Notification, privacy and account preference UI.",active:"Settings",emoji:"⚙️",items:["Email notifications","WhatsApp alerts","Profile visibility"]},
};

const teacherData: Record<string,{title:string;description:string;active:string;emoji:string;items:string[]}> = {
  classes:{title:"Today’s Classes",description:"Manage class schedules, modes, seats and lesson plans.",active:"Today’s Classes",emoji:"📚",items:["Grade 8 theory • 4:00 PM","Grade 9 Zoom • 5:30 PM","Grade 11 paper • 7:30 PM"]},
  students:{title:"Student Management",description:"Search, filter and manage individual student records.",active:"Students",emoji:"👥",items:["Nethmi S. • Grade 10","Kavindu R. • Grade 9","Dinuka P. • Grade 11"]},
  attendance:{title:"Attendance Management",description:"Mark present, absent, late or excused students.",active:"Attendance",emoji:"✅",items:["Grade 10 • Saturday","Grade 9 • Wednesday","Grade 11 • Sunday"]},
  timetable:{title:"Weekly Timetable",description:"Plan physical and Zoom classes across the week.",active:"Weekly Timetable",emoji:"📅",items:["Monday • Grade 8","Wednesday • Grade 9 Zoom","Saturday • Grade 10"]},
  assignments:{title:"Assignment Management",description:"Create tasks, review submissions and add feedback.",active:"Assignments",emoji:"📝",items:["Assignment 06 • 27 submissions","Model Paper 03 • 12 pending","Quiz 04 • Published"]},
  payments:{title:"Payment Approvals",description:"Review payment slips and approve or reject requests.",active:"Payment Approvals",emoji:"💳",items:["Nethmi S. • LKR 3,200","Kavindu R. • LKR 2,800","Dinuka P. • LKR 3,500"]},
  announcements:{title:"Announcement Management",description:"Create, preview, publish and organise class notices.",active:"Announcements",emoji:"📣",items:["Grade 11 seminar","Wednesday time change","Assignment reminder"]},
  profile:{title:"Teacher Profile",description:"Update public teacher information and qualifications.",active:"Profile",emoji:"👨‍🏫",items:["Biography","Qualifications","Social media links"]},
  settings:{title:"Teacher Settings",description:"Portal, notification and class preference UI.",active:"Settings",emoji:"⚙️",items:["Portal notifications","Default class duration","Payment instructions"]},
};

export function PortalSection({role,section}:{role:"student"|"teacher";section:string}){
  const d = role === "student" ? studentData[section] : teacherData[section];
  return <DashboardShell role={role} active={d.active}><div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-sm font-extrabold uppercase tracking-[.18em] text-lavender-600">{role} portal</p><h1 className="mt-2 text-3xl font-black md:text-4xl">{d.title}</h1><p className="mt-2 text-ink/55">{d.description}</p></div><button className="gradient-button">{role==="teacher"?<UserPlus size={17}/>:<Download size={17}/>} {role==="teacher"?"Create new":"Download summary"}</button></div><div className="mt-6 grid gap-4 md:grid-cols-3">{d.items.map((x,i)=><Card className="p-5" key={x}><div className="flex items-start justify-between"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-lavender-100 text-2xl">{d.emoji}</div><button className="text-ink/35"><MoreHorizontal size={19}/></button></div><h2 className="mt-5 text-lg font-black">{x}</h2><div className="mt-3 flex gap-2"><Badge tone={i===0?"pink":i===1?"yellow":"green"}>{i===0?"Action needed":i===1?"In progress":"Completed"}</Badge></div><p className="mt-4 text-sm leading-6 text-ink/55">Realistic placeholder content for this UI section. Connect Firebase services later.</p><button className="mt-5 flex items-center gap-2 text-sm font-black text-lavender-700"><Eye size={16}/> View details</button></Card>)}</div><Card className="mt-6 p-5"><div className="flex flex-col gap-4 md:flex-row md:items-center"><div className="relative flex-1"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-ink/35" size={18}/><input className="pastel-input pl-11" placeholder={`Search ${d.title.toLowerCase()}...`}/></div><button className="pill"><CalendarDays size={17}/> Filter date</button><button className="pill"><FileText size={17}/> Export</button></div><div className="mt-5 overflow-hidden rounded-2xl border border-white/80"><div className="grid grid-cols-[1.2fr_.8fr_.8fr_auto] gap-3 bg-lavender-100 p-4 text-xs font-black uppercase tracking-wide"><span>Item</span><span>Status</span><span>Updated</span><span>Action</span></div>{d.items.concat(d.items).map((x,i)=><div key={i} className="grid grid-cols-[1.2fr_.8fr_.8fr_auto] items-center gap-3 border-t border-white/80 bg-white/45 p-4 text-sm"><span className="font-bold">{x}</span><span><Badge tone={i%2?"green":"yellow"}>{i%2?"Active":"Pending"}</Badge></span><span className="text-ink/45">{i+1} day ago</span><button className="grid h-9 w-9 place-items-center rounded-xl bg-white shadow-card"><MoreHorizontal size={16}/></button></div>)}</div></Card></DashboardShell>
}
