import Link from "next/link";
import { ArrowRight, CalendarDays, CheckCircle2, MessageCircle, Play, Sparkles, Star, Users } from "lucide-react";
import { PublicShell } from "@/components/public-shell";
import { Card, Badge, SectionHeading, TextLink } from "@/components/ui";
import { classes, lessons, announcements, testimonials } from "@/lib/mock-data";
import { createMetadata } from "@/lib/metadata";
import { siteConfig } from "@/lib/site";

export const metadata = createMetadata("Science Tuition Classes", "Colourful, personal Science tuition classes by Pasindu Udana for theory, revision, paper practice and online learning.", "/");

export default function HomePage() {
  const schema = {
    "@context": "https://schema.org", "@type": "Person", name: siteConfig.teacher,
    jobTitle: "Science Tuition Teacher", worksFor: { "@type": "Organization", name: siteConfig.name }, url: siteConfig.url
  };
  return <PublicShell>
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html: JSON.stringify(schema)}} />
    <section className="mx-auto max-w-7xl px-4 pb-12 pt-8 lg:px-8">
      <div className="soft-panel grid-paper relative overflow-hidden p-7 md:p-12 lg:grid lg:grid-cols-[1.1fr_.9fr] lg:items-center lg:gap-12">
        <div className="absolute -left-20 top-16 h-52 w-52 rounded-full bg-lavender-200/70 blur-3xl"/><div className="absolute -right-16 bottom-0 h-64 w-64 rounded-full bg-peach-200/60 blur-3xl"/>
        <div className="relative z-10"><div className="pill"><Sparkles size={16} className="text-lavender-600"/> Student-friendly Science learning</div><h1 className="mt-6 text-4xl font-black leading-[1.06] tracking-tight md:text-6xl">Make Science <span className="text-lavender-600">simple, interesting</span> and successful.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-ink/65">Join Pasindu Udana for clear theory explanations, practical examples, revision activities, assignments, model papers and regular progress monitoring.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/timetable" className="gradient-button"><CalendarDays size={18}/> View Class Schedule</Link><Link href="/free-lessons" className="pill"><Play size={17}/> Watch Free Lessons</Link><Link href="/contact" className="pill"><MessageCircle size={17}/> WhatsApp Sir</Link></div><div className="mt-7 flex flex-wrap gap-5 text-sm font-bold text-ink/55"><span className="flex items-center gap-2"><CheckCircle2 size={17} className="text-emerald-500"/> Grades 8–11</span><span className="flex items-center gap-2"><CheckCircle2 size={17} className="text-emerald-500"/> Sinhala & English medium</span><span className="flex items-center gap-2"><CheckCircle2 size={17} className="text-emerald-500"/> Physical + Zoom</span></div></div>
        <div className="relative mt-10 lg:mt-0"><div className="mx-auto max-w-md rounded-[2.2rem] bg-gradient-to-b from-lavender-200 to-[#bea1ef] p-5 shadow-soft"><div className="relative overflow-hidden rounded-[1.8rem] bg-white/45 p-6 text-center"><div className="absolute left-4 top-5 text-4xl animate-float">🧬</div><div className="absolute right-5 top-8 text-4xl animate-float">⚛️</div><div className="mx-auto grid h-56 w-56 place-items-center rounded-full bg-gradient-to-br from-peach-100 via-white to-lavender-100 text-8xl shadow-card">👨‍🏫</div><h2 className="mt-5 text-2xl font-black">Pasindu Udana</h2><p className="text-sm font-semibold text-ink/55">Science Teacher • Mentor • Paper Class Instructor</p></div></div><div className="absolute -bottom-5 -left-2 rounded-3xl bg-butter p-4 shadow-card"><strong className="block text-2xl">92%</strong><span className="text-xs font-bold text-ink/55">student attendance</span></div></div>
      </div>
    </section>

    <section className="mx-auto max-w-7xl px-4 py-10 lg:px-8"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{[["450+","Active students","👩‍🎓"],["8+","Years teaching","🏆"],["120+","Free lessons","▶️"],["90%","Improved results","📈"],["14","Weekly classes","📅"]].map(([v,l,e])=><Card key={l} className="p-5 text-center"><div className="text-3xl">{e}</div><p className="mt-2 text-3xl font-black">{v}</p><p className="text-sm font-bold text-ink/50">{l}</p></Card>)}</div></section>

    <section className="mx-auto max-w-7xl px-4 py-14 lg:px-8"><SectionHeading eyebrow="Available classes" title="Choose the class that fits your learning goal" text="Theory, revision, paper practice and hybrid learning options are organised by grade."/><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">{classes.map((c,i)=><Card key={c.title+c.grade} className="p-6"><div className="flex items-center justify-between"><Badge tone={i%2?"pink":"lavender"}>{c.grade}</Badge><Badge tone={c.mode==="Online"?"blue":"green"}>{c.mode}</Badge></div><div className="mt-5 text-4xl">{["🔭","🧠","🧪","📝"][i]}</div><h3 className="mt-4 text-xl font-black">{c.title}</h3><div className="mt-4 space-y-2 text-sm text-ink/60"><p><strong className="text-ink">{c.day}</strong> • {c.time}</p><p>{c.location}</p><p>{c.fee} / month</p><p>{c.seats} seats remaining</p></div><Link href="/contact" className="gradient-button mt-5 w-full">Enrol now <ArrowRight size={17}/></Link></Card>)}</div><div className="mt-6"><TextLink href="/classes">View every class</TextLink></div></section>

    <section className="mx-auto max-w-7xl px-4 py-14 lg:px-8"><div className="soft-panel p-7 md:p-10"><SectionHeading eyebrow="Why students choose this class" title="A complete learning system, not only a weekly lecture"/><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{["Simple explanations","Complete syllabus","Weekly assignments","Model papers","Progress monitoring","Recorded lessons","Exam preparation","WhatsApp support","Parent updates","Zoom classes"].map((x,i)=><div key={x} className="rounded-2xl bg-white/70 p-4 shadow-card"><div className="mb-3 grid h-10 w-10 place-items-center rounded-xl bg-lavender-100 text-lg">{["💡","📚","✍️","📄","📊","🎥","🎯","💬","👪","💻"][i]}</div><p className="font-black">{x}</p></div>)}</div></div></section>

    <section className="mx-auto max-w-7xl px-4 py-14 lg:px-8"><SectionHeading eyebrow="Free lessons" title="Start learning before joining" text="Explore sample video lessons and downloadable notes for different grades."/><div className="grid gap-5 md:grid-cols-3">{lessons.map((l,i)=><Card key={l.title} className="overflow-hidden"><div className={`grid h-44 place-items-center text-7xl ${["bg-lavender-200","bg-peach-100","bg-butter"][i]}`}>{l.icon}</div><div className="p-5"><div className="flex gap-2"><Badge>{l.grade}</Badge><Badge tone="blue">{l.duration}</Badge></div><h3 className="mt-4 text-xl font-black">{l.title}</h3><p className="mt-1 text-sm text-ink/50">{l.topic} with Pasindu Udana</p><Link href="/free-lessons" className="gradient-button mt-5 w-full"><Play size={16}/> Watch free</Link></div></Card>)}</div></section>

    <section className="mx-auto grid max-w-7xl gap-6 px-4 py-14 lg:grid-cols-2 lg:px-8"><div><SectionHeading eyebrow="Latest updates" title="Announcements for students and parents"/>{announcements.map(a=><Card key={a.title} className="mb-4 flex items-center gap-4 p-5"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-peach-100 text-xl">📣</div><div className="min-w-0 flex-1"><div className="flex flex-wrap gap-2"><Badge tone="pink">{a.category}</Badge><Badge tone="yellow">{a.priority}</Badge></div><h3 className="mt-2 font-black">{a.title}</h3><p className="text-xs text-ink/45">{a.date}</p></div></Card>)}</div><div><SectionHeading eyebrow="Student success" title="What our learners say"/>{testimonials.map(t=><Card key={t.name} className="mb-4 p-5"><div className="flex items-center justify-between"><div><p className="font-black">{t.name}</p><p className="text-xs text-ink/45">{t.grade}</p></div><div className="flex text-amber-400">{Array.from({length:t.rating}).map((_,i)=><Star key={i} size={15} fill="currentColor"/>)}</div></div><p className="mt-4 text-sm leading-6 text-ink/65">“{t.text}”</p></Card>)}</div></section>

    <section className="mx-auto max-w-7xl px-4 py-12 lg:px-8"><div className="relative overflow-hidden rounded-[2.2rem] bg-gradient-to-r from-lavender-600 to-[#a36ee9] p-8 text-white shadow-soft md:p-12"><div className="absolute right-8 top-1/2 -translate-y-1/2 text-8xl opacity-25">⚛️</div><div className="relative max-w-2xl"><p className="font-extrabold uppercase tracking-[.2em] text-white/70">Ready to begin?</p><h2 className="mt-3 text-3xl font-black md:text-5xl">Join Pasindu Udana’s Science class today.</h2><p className="mt-4 leading-7 text-white/75">View the timetable, ask about available seats and choose a physical or online class.</p><div className="mt-6 flex flex-wrap gap-3"><Link href="/contact" className="rounded-2xl bg-white px-5 py-3 font-black text-lavender-700 shadow-card">Contact Sir</Link><Link href="/student-login" className="rounded-2xl bg-white/15 px-5 py-3 font-black text-white ring-1 ring-white/30">Student Login</Link></div></div></div></section>
  </PublicShell>
}
